light:
  - arrow-down
  - arrow-up
  - building-flag
  - chalkboard-user
  - check
  - chevron-right
  - ellipsis-vertical
  - eye
  - gear
  - hand-point-right
  - headset
  - mobile
  - pencil
  - print
  - qrcode
  - sitemap
  - trash
  - user
  - user-gear
  - user-shield
  - users
regular:
  - angle-left