regular:
  - building-flag
  - chalkboard-user
  - check
  - chevron-right
  - eye
  - hand-point-right
  - mobile
  - pencil
  - print
  - qrcode
  - sitemap
  - trash
  - user-gear
  - user-shield
  - users